development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: bueschernico@gmail.com
  :password: mnGPasswort?
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: bueschernico@gmail.com
  :password: mnGPasswort?
  :enable_starttls_auto: true
