require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe BandsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Band. As you add validations to Band, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BandsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all bands as @bands" do
      band = Band.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:bands)).to eq([band])
    end
  end

  describe "GET show" do
    it "assigns the requested band as @band" do
      band = Band.create! valid_attributes
      get :show, {:id => band.to_param}, valid_session
      expect(assigns(:band)).to eq(band)
    end
  end

  describe "GET new" do
    it "assigns a new band as @band" do
      get :new, {}, valid_session
      expect(assigns(:band)).to be_a_new(Band)
    end
  end

  describe "GET edit" do
    it "assigns the requested band as @band" do
      band = Band.create! valid_attributes
      get :edit, {:id => band.to_param}, valid_session
      expect(assigns(:band)).to eq(band)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Band" do
        expect {
          post :create, {:band => valid_attributes}, valid_session
        }.to change(Band, :count).by(1)
      end

      it "assigns a newly created band as @band" do
        post :create, {:band => valid_attributes}, valid_session
        expect(assigns(:band)).to be_a(Band)
        expect(assigns(:band)).to be_persisted
      end

      it "redirects to the created band" do
        post :create, {:band => valid_attributes}, valid_session
        expect(response).to redirect_to(Band.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved band as @band" do
        post :create, {:band => invalid_attributes}, valid_session
        expect(assigns(:band)).to be_a_new(Band)
      end

      it "re-renders the 'new' template" do
        post :create, {:band => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested band" do
        band = Band.create! valid_attributes
        put :update, {:id => band.to_param, :band => new_attributes}, valid_session
        band.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested band as @band" do
        band = Band.create! valid_attributes
        put :update, {:id => band.to_param, :band => valid_attributes}, valid_session
        expect(assigns(:band)).to eq(band)
      end

      it "redirects to the band" do
        band = Band.create! valid_attributes
        put :update, {:id => band.to_param, :band => valid_attributes}, valid_session
        expect(response).to redirect_to(band)
      end
    end

    describe "with invalid params" do
      it "assigns the band as @band" do
        band = Band.create! valid_attributes
        put :update, {:id => band.to_param, :band => invalid_attributes}, valid_session
        expect(assigns(:band)).to eq(band)
      end

      it "re-renders the 'edit' template" do
        band = Band.create! valid_attributes
        put :update, {:id => band.to_param, :band => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested band" do
      band = Band.create! valid_attributes
      expect {
        delete :destroy, {:id => band.to_param}, valid_session
      }.to change(Band, :count).by(-1)
    end

    it "redirects to the bands list" do
      band = Band.create! valid_attributes
      delete :destroy, {:id => band.to_param}, valid_session
      expect(response).to redirect_to(bands_url)
    end
  end

end
